### ISSUE TITLE
Could not resolve net.amcintosh:freshbooks-sdk:0.5.0.

### ISSUE THREAD

**Issue by Jesse-Weel** [amcintosh/freshbooks-java-sdk#40]
Hello, I am building software in Java that needs to integrate with freshbooks; and I am trying to use your sdk... When I include the gradle implementation line and run the gradle build, I am getting an error (issue title): `Could not resolve net.amcintosh:freshbooks-sdk:0.5.0.`

I've tried explicitly defining your git repo in my settings.gradle like so:
`sourceControl {
    gitRepository("https://github.com/amcintosh/freshbooks-java-sdk.git") {
        producesModule("net.amcintosh:freshbooks-sdk")
    }
}`

This gets me a different error:
`Could not find any version that matches net.amcintosh:freshbooks-sdk:0.5.0.
     Searched in the following locations:
       - Git repository at https://github.com/amcintosh/freshbooks-java-sdk.git`

**Comment by amcintosh** [comment]
Hi. The package should be available in the Maven Central Repository. 

What does your build.gradle look like?

I setup a simple project and was able to fetch it.

build.gradle:

```groovy
plugins {
    id 'java'
}

group 'demo.amcintosh'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.amcintosh:freshbooks-sdk:0.5.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}
```

**Comment by Jesse-Weel** [comment]
Yes I thought it should be...

build.gradle:
`plugins {
    id 'org.springframework.boot' version '2.2.1.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
    id 'java'
    id 'groovy'
}

group 'com.weel'
version '1.0-SNAPSHOT'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    all*.exclude group: 'org.springframework.boot',
            module: 'spring-boot-starter-logging'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jetbrains:annotations:20.1.0'
    compile 'org.codehaus.groovy:groovy-all:2.3.11'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'net.amcintosh:freshbooks-sdk:0.5.0'
    compile 'org.springframework:spring-jdbc:5.2.1.RELEASE'
    compile 'org.springframework:spring-orm:5.1.9.RELEASE'
    compile 'org.springframework.boot:spring-boot-starter-log4j2:2.3.4.RELEASE'
    compile 'org.hibernate:hibernate-core:5.4.9.Final'
    compile 'org.springframework.data:spring-data-jpa:2.2.1.RELEASE'
    compile 'org.hibernate.validator:hibernate-validator:6.0.17.Final'
    compile 'javax.el:javax.el-api:3.0.0' // Added as a Hibernate Validator dependency
    compile 'com.zaxxer:HikariCP:3.4.1'
    compile 'org.postgresql:postgresql:42.2.8'
    compile 'org.hsqldb:hsqldb:2.5.0'
    compile 'com.amazonaws:aws-java-sdk-s3:1.11.683'
    compile 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.3'
    compile 'com.stripe:stripe-java:21.4.0'
    compile 'com.google.code.gson:gson:2.9.1'
    compile 'com.sendgrid:sendgrid-java:4.9.3'
    compile 'com.fasterxml.jackson.core:jackson-core:2.13.3'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.13.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.13.3'
    compile 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.3'
    compile 'com.sendgrid:java-http-client:4.5.0'
    compile 'org.bouncycastle:bcprov-jdk15on:1.70'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.5.2'
    testCompile 'org.mockito:mockito-core:3.1.0'
    testCompile 'org.mockito:mockito-junit-jupiter:3.1.0'
}
`

**Comment by Jesse-Weel** [comment]
Yes, that was the issue... I had to upgrade to Java 17 to get it to work. My mistake; sorry

**Comment by amcintosh** [comment]
Not a problem. Glad it's working!
